feat(rpc): discover rpc url automaticaly for event / message
Arianee/arianeeJS pull request #297
Opened 2020-09-23 15:14 UTC by gnarco

2020-09-24 08:57 UTC, stefdelec requested changes

2020-09-24 08:57 UTC, stefdelec commented on src/core/wallet/services/eventService/eventsService.ts
> +    if (!url) {
ca ne va pas marcher
url:string = '' ==> url?:string
Sinon url sera toujours défini

2020-09-24 08:57 UTC, stefdelec commented on src/core/wallet/services/messageService/messageService.ts
> +    if (!url) {
idem que plus haut

2020-09-25 12:25 UTC, mvaullerin approved these changes

2020-09-25 12:33 UTC, merged